[Infra] Docs: update starter pack configuration files to 1.2.0 (#260)

diff --git a/docs/.readthedocs.yaml b/docs/.readthedocs.yaml
--- a/docs/.readthedocs.yaml
+++ b/docs/.readthedocs.yaml
@@ -14,7 +14,17 @@ build:
     python: "3.12"
   jobs:
     post_checkout:
-      - cd docs && python3 .sphinx/build_requirements.py
+      # Unshallow the git clone to provide history for sphinx-last-updated-by-git
+      - git fetch --unshallow || true
+      # Cancel building pull requests when there aren't changed in the docs directory.
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' 'yarf/';
+        then
+          exit 183;
+        fi
       # Support Git LFS: Download and uncompress the binary
       # https://docs.readthedocs.io/en/stable/build-customization.html#support-git-lfs-large-file-storage
       - wget https://github.com/git-lfs/git-lfs/releases/download/v3.5.1/git-lfs-linux-amd64-v3.5.1.tar.gz
@@ -45,4 +55,6 @@ formats:
 # Optionally declare the Python requirements required to build your docs
 python:
    install:
-     - requirements: docs/.readthedocs-requirements.txt
+     - requirements: docs/.sphinx/requirements.txt
+     - method: pip
+       path: .    # Installs YARF itself used by scripts in .sphinx/rf_libraries/
